plugins:
  - jekyll-relative-links
  - jekyll-katex
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
kramdown:
  math_engine: katex
katex:
theme: jekyll-theme-cayman
